### ISSUE TITLE
[Report] Meta 划词菜单(搜索+翻译+保存+转到)#17

### ISSUE THREAD

**Issue by 1074305015** [ikkz/bext-meta#54]
请前往 https://github.com/ikkz/bext-meta/commits/master/meta/17.json
选择一位或者多位你认为能解决你问题的脚本作者，并在问题描述之后 at
问题描述：用不了，安装后没任何作用

**Comment by forcux** [comment]
这边测试了，没有问题啊。

麻烦报下 
1. 安装选项 (如果手动改了的话)
2. 浏览器
3. 目标网页链接
以及 (尤其是 Via) 关闭其它所有脚本再试试呢

@1074305015 @yzy-2019

**Comment by 1074305015** [comment]
感谢回复。我把脚本都关了可以使用，再逐个打开脚本，发现与 网页弹窗拦截 这个脚本冲突。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月18日(周三) 中午12:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ikkz/bext-meta] [Report] Meta 划词菜单(搜索+翻译+保存+转到)#17 (Issue #54)




 
这边测试了，没有问题啊。
 
麻烦报下
  
安装选项 (如果手动改了的话) 

浏览器 

目标网页链接
 以及 (尤其是 Via) 关闭其它所有脚本再试试呢 
 
@1074305015 @yzy-2019

**Comment by forcux** [comment]
这两个脚本我来回安装测试了几次，确认它们没有冲突。  

由于 Via 会把所有脚本拼在一起执行，一个报错后面统统都停了。  

所以问题很复杂，，，  

如果你有条件，可以电脑 inspect ，或者最先安装 Eruda / vConsole ，  
也许能弄出些控制台错误信息，找到些线索  

否则我也没办法弄清楚问题出在哪里 @_@

**Comment by forcux** [comment]
已经确定是 轻插件 版本的 网页弹窗拦截 脚本的问题。
前几天此脚本作者已经更新脚本修复了此问题。
